# OneData/bots/ONEBOT/config/modules/Core/AccessRolesHub.conf
# Purpose: AccessRoles hub pointer config.

# CORE
enabled=1
implFile=modules/Core/AccessRoles/AccessRolesCV.js
implConfig=modules/Core/Impl/AccessRolesCV.conf