# OneData/bots/ONEBOT/config/modules/Core/BootAnnounceHub.conf
# Purpose: BootAnnounce hub pointer config.

# CORE
enabled=1
implFile=modules/Core/BootAnnounce/BootAnnounceCV.js
implConfig=modules/Core/Impl/BootAnnounceCV.conf