# OneData/bots/ONEBOT/config/modules/Core/CommandHub.conf
# Purpose: Command hub pointer config.

# CORE
enabled=1
implFile=modules/Core/Command/CommandCV.js
implConfig=modules/Core/Impl/CommandCV.conf