# OneData/bots/ONEBOT/config/modules/Core/InboundDedupeHub.conf
# Purpose: InboundDedupe hub pointer config.

# CORE
enabled=1
implFile=modules/Core/InboundDedupe/InboundDedupeCV.js
implConfig=modules/Core/Impl/InboundDedupeCV.conf