# OneData/bots/ONEBOT/config/modules/Core/InboundFilterHub.conf
# Purpose: InboundFilter hub pointer config.

# CORE
enabled=1
implFile=modules/Core/InboundFilter/InboundFilterCV.js
implConfig=modules/Core/Impl/InboundFilterCV.conf