# OneData/bots/ONEBOT/config/modules/Core/InstanceLockHub.conf
# Purpose: InstanceLock hub pointer config.

# CORE
enabled=1
implFile=modules/Core/InstanceLock/InstanceLockCV.js
implConfig=modules/Core/Impl/InstanceLockCV.conf