# OneData/bots/ONEBOT/config/modules/Core/JsonStoreHub.conf
# Purpose: JsonStore hub pointer config.

# CORE
enabled=1
implFile=modules/Core/JsonStore/JsonStoreCV.js
implConfig=modules/Core/Impl/JsonStoreCV.conf