# OneData/bots/ONEBOT/config/modules/Core/Impl/LibraryCV.conf
# Purpose: Log hub pointer config.

# CORE
enabled=1
implFile=Modules/Core/Library/LibraryCV.js
implConfig=modules/Core/Impl/LibraryCV.conf