# OneData/bots/ONEBOT/config/modules/Core/LibraryHub.conf
# Purpose: Library hub pointer config.

# CORE
enabled=1
implFile=modules/Core/Library/LibraryCV.js
implConfig=modules/Core/Impl/LibraryCV.conf