# OneData/bots/ONEBOT/config/modules/Core/MessageJournalHub.conf
# Purpose: MessageJournal hub pointer config.

# CORE
enabled=1
implFile=modules/Core/MessageJournal/MessageJournalCV.js
implConfig=modules/Core/Impl/MessageJournalCV.conf