# OneData/bots/ONEBOT/config/modules/Core/OutboxHub.conf
# Purpose: Outbox hub pointer config.

# CORE
enabled=1
implFile=modules/Core/Outbox/OutboxCV.js
implConfig=modules/Core/Impl/OutboxCV.conf