# OneData/bots/ONEBOT/config/modules/Core/OutboundGatewayHub.conf
# Purpose: OutboundGateway hub pointer config.

# CORE
enabled=1
implFile=modules/Core/OutboundGateway/OutboundGatewayCV.js
implConfig=modules/Core/Impl/OutboundGatewayCV.conf