# OneData/bots/ONEBOT/config/modules/Core/PingDiagHub.conf
# Purpose: PingDiag hub pointer config.

# CORE
enabled=1
implFile=modules/Core/PingDiag/PingDiagCV.js
implConfig=modules/Core/Impl/PingDiagCV.conf