# OneData/bots/ONEBOT/config/modules/Core/RateLimitHub.conf
# Purpose: RateLimit hub pointer config.

# CORE
enabled=1
implFile=modules/Core/RateLimit/RateLimitCV.js
implConfig=modules/Core/Impl/RateLimitCV.conf