# OneData/bots/ONEBOT/config/modules/Core/SchedulerHub.conf
# Purpose: Scheduler hub pointer config.

# CORE
enabled=1
implFile=modules/Core/Scheduler/SchedulerCV.js
implConfig=modules/Core/Impl/SchedulerCV.conf