# OneData/bots/ONEBOT/config/modules/Core/SendQueueHub.conf
# Purpose: SendQueue hub pointer config.

# CORE
enabled=1
implFile=modules/Core/SendQueue/SendQueueCV.js
implConfig=modules/Core/Impl/SendQueueCV.conf