# OneData/bots/ONEBOT/config/modules/Core/SendPolicyHub.conf
# Purpose: SendPolicy hub pointer config.

# CORE
enabled=1
implFile=modules/Core/SendPolicy/SendPolicyCV.js
implConfig=modules/Core/Impl/SendPolicyCV.conf