# OneData/bots/ONEBOT/config/modules/Core/StatusFeedHub.conf
# Purpose: StatusFeed hub pointer config.

# CORE
enabled=1
implFile=modules/Core/StatusFeed/StatusFeedCV.js
implConfig=modules/Core/Impl/StatusFeedCV.conf