# OneData/bots/ONEBOT/config/modules/Core/TimeZoneHub.conf
# Purpose: TimeZone hub pointer config.

# CORE
enabled=1
implFile=modules/Core/TimeZone/TimeZoneCV.js
implConfig=modules/Core/Impl/TimeZoneCV.conf