# OneData/bots/ONEBOT/config/modules/Core/WorkGroupsHub.conf
# Purpose: WorkGroups hub pointer config.

# CORE
enabled=1
implFile=modules/Core/WorkGroups/WorkGroupsCV.js
implConfig=modules/Core/Impl/WorkGroupsCV.conf