# OneData/bots/ONEBOT/config/modules/Core/Impl/BootAnnounceCV.conf
# Purpose: Boot announcement CV implementation config.

# CORE SWITCHES
enabled=1
globalConfRel=modules/Core/Impl/GlobalCV.conf

# MODULE LOGGING TOGGLES
moduleLog=1
bugLog=1
detailLog=0
traceLog=0

# ANNOUNCE CONTENT
delayMs=2000
botName=ONEBOT
title=ONEBOT Online
tips=!status | !help | !roles | !ping

# SERVICE WIRING
serviceName=sendout