# OneData/bots/ONEBOT/config/modules/Core/Impl/ContactBookCV.conf
# Purpose: ContactBook CV skeleton implementation config.

# CORE
enabled=1
globalConfRel=modules/Core/Impl/GlobalCV.conf

# LOGGING
moduleLog=1
bugLog=1
detailLog=0
traceLog=0