# GLOBAL CV CONFIG
# Shared values for core modules.

# GLOBAL IDENTITY
controlGroupId=120363402608825006@g.us
timeZone=Asia/Kuala_Lumpur
locale=en-MY
hour12=0
prefix=!

# SHARED DATA DIRS (RELATIVE TO meta.dataRootBot)
logBaseDirRel=logs
jsonStoreBaseDirRel=JsonStore

# SHARED SERVICE PREFERENCE
sendPrefer=sendout,outsend,send