# OneData/bots/ONEBOT/config/modules/Core/Impl/InboundFilterCV.conf
# Purpose: InboundFilter CV implementation config.

# Global reference
globalConfRel=modules/Core/Impl/GlobalCV.conf

# Module toggle
enabled=1

# Logging toggles
moduleLog=1
bugLog=1
detailLog=0
traceLog=0

# Filter controls
dropStatusBroadcast=0
dropEmptySystem=1
dropFromMe=0