# OneData/bots/ONEBOT/config/modules/Core/Impl/InboundFilterCV.conf
# Purpose: InboundFilter CV implementation config.

# CORE SWITCHES
enabled=1
globalConfRel=modules/Core/Impl/GlobalCV.conf

# MODULE LOGGING TOGGLES
moduleLog=1
bugLog=1
detailLog=0
traceLog=0

# FILTER CONTROLS
dropStatusBroadcast=0
dropEmptySystem=1
dropFromMe=0