# OneData/bots/ONEBOT/config/modules/Core/Impl/JsonStoreCV.conf
# Purpose: JsonStore CV implementation config.

# CORE SWITCHES
enabled=1
globalConfRel=modules/Core/Impl/GlobalCV.conf

# MODULE LOGGING TOGGLES
moduleLog=1
bugLog=1
detailLog=0
traceLog=0

# STORAGE
namespace=core
dir=
flushDelayMs=100