# OneData/bots/ONEBOT/config/modules/Core/Impl/SendPolicyCV.conf
# Purpose: SendPolicy CV implementation config.

# CORE
enabled=1
globalConfRel=modules/Core/Impl/GlobalCV.conf
defaultProfile=normal
serviceName=sendpolicy.getProfile

# LOGGING
moduleLog=1
bugLog=1
detailLog=0
traceLog=0