# OneData/bots/ONEBOT/config/modules/Core/Impl/TimeZoneCV.conf
# Purpose: TimeZone CV implementation config.

# CORE
enabled=1
globalConfRel=modules/Core/Impl/GlobalCV.conf

# FORMAT OPTIONS
dateStyle=short
timeStyle=medium

# MODULE LOGGING TOGGLES
moduleLog=1
bugLog=1
detailLog=0
traceLog=0